### ISSUE TITLE
Updated blocklists

### ISSUE THREAD

**Issue by bhoglan** [SwaroopGiri/Pi_hole_configuration#1]
I'm not able to create a branch due to permissions, but I have an updated readme.md for you if you'd like. I ran into a number of adlists on the blocklist side that no longer exist. I pulled them out of the file to create a PR for you. I'll just attach it here for you.
[README.md](https://github.com/SwaroopGiri/Pi_hole_configuration/files/11560503/README.md)

**Comment by SwaroopGiri** [comment]
Thanks for your efforts, I've created a PR and will merge it in a couple of days.
